import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const AuctionCardStyles = StyleSheet.create({
  auctionCard: {
    borderRadius: 16,
    marginBottom: 18,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    overflow: "hidden",
  },
  cardHeader: {
    position: "relative",
  },
  stallImage: {
    width: "100%",
    height: 200,
    backgroundColor: "#F3F4F6",
  },
  heartIcon: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "#FFFFFF",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  heartText: {
    fontSize: 18,
    color: "#EF4444",
  },
  auctionBadge: {
    position: "absolute",
    top: 15,
    left: 15,
    backgroundColor: "#1E9C00",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  auctionBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  cardContent: {
    padding: 20,
  },
  stallInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  stallNumberContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 25,
  },
  stallLabel: {
    fontSize: 11,
    fontWeight: "700",
    marginRight: 4,
    letterSpacing: 0.3,
  },
  stallNumber: {
    fontSize: 15,
    fontWeight: "bold",
  },
  locationContainer: {
    backgroundColor: "#002181",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: "#002181",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  locationText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  startingPriceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    padding: 14,
    borderRadius: 12,
    borderLeftWidth: 5,
  },
  startingPriceLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  startingPriceText: {
    fontSize: 20,
    fontWeight: "800",
  },
  detailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  floorText: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 0,
  },
  sizeText: {
    fontSize: 14,
    fontWeight: "500",
  },
  stallDescriptionContainer: {
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
  },
  stallDescriptionLabel: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 6,
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 22,
  },
  auctionDateContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderRadius: 12,
    marginBottom: 18,
    borderLeftWidth: 5,
  },
  auctionDateLabel: {
    fontSize: 12,
    fontWeight: "600",
  },
  auctionDateText: {
    fontSize: 14,
    fontWeight: "bold",
    lineHeight: 20,
    flexWrap: "wrap",
  },
  statusButton: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statusButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 0.3,
  },
  preRegisterButton: {
    marginBottom: 12,
  },
  preRegisterButtonText: {},
  placeBidButton: {
    marginTop: 4,
    marginBottom: 4,
  },
  placeBidButtonDisabled: {
    opacity: 0.6,
  },
  placeBidButtonText: {
    textAlign: "center",
  },
  placeBidButtonTextDisabled: {
    fontWeight: "500",
  },
  buttonContent: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 24,
    paddingVertical: 2,
  },
  countdownText: {
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
    textAlign: "center",
    fontStyle: "italic",
  },
  countdownTextDisabled: {
    opacity: 0.7,
  },
  disabledButton: {
    opacity: 0.6,
  },
});
