import { StyleSheet, Dimensions, Platform } from "react-native";
const { width, height } = Dimensions.get("window");

export const ProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  backButton: {
    position: "absolute",
    top: height * 0.02,
    left: width * 0.02,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 1,
  },
  backButtonText: {
    color: "#fff",
    fontSize: width * 0.04,
    marginLeft: 4,
    fontWeight: "500",
  },
  editButton: {
    position: "absolute",
    top: height * 0.02,
    right: width * 0.02,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3b82f6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 1,
  },
  editButtonText: {
    color: "#fff",
    fontSize: width * 0.04,
    marginLeft: 4,
    fontWeight: "500",
  },
  header: {
    backgroundColor: "#1f2937",
    alignItems: "center",
    paddingVertical: height * 0.04,
    paddingHorizontal: width * 0.06,
  },
  avatarContainer: {
    width: width * 0.2,
    height: width * 0.2,
    borderRadius: width * 0.1,
    backgroundColor: "#3b82f6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: height * 0.015,
  },
  avatarText: {
    fontSize: width * 0.08,
    fontWeight: "bold",
    color: "white",
  },
  profileName: {
    fontSize: width * 0.06,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    marginBottom: height * 0.005,
  },
  profileEmail: {
    fontSize: width * 0.04,
    color: "#9ca3af",
    textAlign: "center",
  },
  section: {
    backgroundColor: "white",
    marginHorizontal: width * 0.04,
    marginTop: height * 0.02,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: width * 0.05,
    fontWeight: "bold",
    color: "#1f2937",
    padding: width * 0.04,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  sectionContent: {
    padding: width * 0.04,
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: height * 0.015,
    alignItems: "flex-start",
  },
  label: {
    fontSize: width * 0.04,
    fontWeight: "600",
    color: "#374151",
    width: "40%",
    marginRight: width * 0.02,
  },
  value: {
    fontSize: width * 0.04,
    color: "#6b7280",
    flex: 1,
    textAlign: "right",
  },
  footer: {
    alignItems: "center",
    paddingVertical: height * 0.03,
    paddingHorizontal: width * 0.06,
  },
  footerText: {
    fontSize: width * 0.035,
    color: "#9ca3af",
    fontStyle: "italic",
  },
});
