# DigitalOcean App Platform Configuration
# DigiStall - Stall Management System

name: digistall

# Region - Singapore for best latency to Philippines
region: sgp

# ===== SERVICES =====
services:
  # Backend API Service
  - name: digistall-api
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/DigiStall-CP2025-2026
    source_dir: /Backend/Backend-Web
    dockerfile_path: ../Dockerfile
    http_port: 3001
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /api
    envs:
      # Server Configuration
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: WEB_PORT
        value: "3001"
        scope: RUN_TIME
      # Database Configuration (DigitalOcean Managed Database)
      - key: DB_HOST
        value: ${digistall-db.HOSTNAME}
        scope: RUN_TIME
      - key: DB_PORT
        value: ${digistall-db.PORT}
        scope: RUN_TIME
      - key: DB_USER
        value: ${digistall-db.USERNAME}
        scope: RUN_TIME
      - key: DB_PASSWORD
        value: ${digistall-db.PASSWORD}
        scope: RUN_TIME
      - key: DB_NAME
        value: ${digistall-db.DATABASE}
        scope: RUN_TIME
      - key: DB_SSL
        value: "true"
        scope: RUN_TIME
      # JWT Configuration
      - key: JWT_SECRET
        type: SECRET
        value: your-super-secret-jwt-key-change-this-in-production
        scope: RUN_TIME
      - key: JWT_REFRESH_SECRET
        type: SECRET
        value: your-refresh-secret-key-change-this-in-production
        scope: RUN_TIME

# ===== STATIC SITES =====
static_sites:
  # Frontend Web Application
  - name: digistall-web
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/DigiStall-CP2025-2026
    source_dir: /Frontend/Web
    build_command: npm install && npm run build
    output_dir: dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api
        scope: BUILD_TIME

# ===== DATABASES =====
databases:
  - name: digistall-db
    engine: MYSQL
    version: "8"
    production: false
    cluster_name: digistall-mysql
    db_name: naga_stall
    db_user: doadmin

# ===== ALERTS =====
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
