import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

// function that creates themed styles
export const AboutStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    flex: 1,
  },
  headerGradient: {
    paddingTop: height * 0.02,
    paddingBottom: height * 0.04,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginLeft: width * 0.04,
    marginBottom: height * 0.02,
  },
  backButtonText: {
    color: "#fff",
    fontSize: width * 0.038,
    marginLeft: 6,
    fontWeight: "500",
  },
  headerContent: {
    alignItems: "center",
    paddingHorizontal: width * 0.06,
  },
  appIconWrapper: {
    marginBottom: height * 0.015,
  },
  appIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  appName: {
    fontSize: width * 0.07,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 6,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  appSubtitle: {
    fontSize: width * 0.04,
    color: "rgba(255, 255, 255, 0.9)",
    textAlign: "center",
    marginBottom: height * 0.015,
  },
  versionBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  versionText: {
    color: "#fff",
    fontSize: width * 0.035,
    fontWeight: "600",
  },
  contentArea: {
    paddingHorizontal: width * 0.04,
    paddingTop: height * 0.025,
  },
  descriptionCard: {
    backgroundColor: theme.colors.card,
    padding: width * 0.045,
    borderRadius: 18,
    marginBottom: height * 0.018,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    borderWidth: 1,
    borderColor: theme.isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
  },
  descriptionText: {
    fontSize: width * 0.04,
    color: theme.colors.text,
    lineHeight: width * 0.06,
    textAlign: "center",
  },
  section: {
    backgroundColor: theme.colors.card,
    marginBottom: height * 0.018,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: width * 0.045,
    paddingVertical: height * 0.018,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.isDark ? 'rgba(255,255,255,0.1)' : 'rgba(26, 35, 126, 0.08)',
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : 'rgba(26, 35, 126, 0.04)',
  },
  sectionTitle: {
    fontSize: width * 0.042,
    fontWeight: "700",
    color: theme.colors.text,
    marginLeft: 12,
    letterSpacing: 0.3,
  },
  sectionContent: {
    paddingHorizontal: width * 0.045,
    paddingVertical: height * 0.012,
  },
  featuresList: {
    marginTop: 4,
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: height * 0.012,
    borderBottomWidth: 1,
    borderBottomColor: theme.isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
  },
  featureIconContainer: {
    marginRight: 12,
  },
  featureText: {
    fontSize: width * 0.038,
    color: theme.colors.text,
    flex: 1,
    lineHeight: width * 0.055,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: height * 0.015,
    borderBottomWidth: 1,
    borderBottomColor: theme.isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
  },
  lastContactItem: {
    borderBottomWidth: 0,
  },
  contactIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  contactTextContainer: {
    flex: 1,
  },
  contactLabel: {
    fontSize: width * 0.038,
    fontWeight: "600",
    color: theme.colors.text,
    marginBottom: 2,
  },
  contactValue: {
    fontSize: width * 0.035,
    color: theme.colors.textSecondary,
  },
  developerCard: {
    alignItems: "center",
    paddingVertical: height * 0.015,
  },
  developerText: {
    fontSize: width * 0.038,
    color: theme.colors.text,
    textAlign: "center",
    marginTop: 12,
    marginBottom: 12,
    lineHeight: width * 0.055,
  },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.1)' : 'rgba(26, 35, 126, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  locationText: {
    fontSize: width * 0.035,
    color: theme.colors.textSecondary,
    marginLeft: 6,
  },
  legalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: height * 0.015,
    borderBottomWidth: 1,
    borderBottomColor: theme.isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
  },
  lastLegalItem: {
    borderBottomWidth: 0,
  },
  legalText: {
    fontSize: width * 0.038,
    color: theme.colors.primary,
    fontWeight: "500",
  },
  copyrightSection: {
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.03,
    alignItems: "center",
  },
  copyrightText: {
    fontSize: width * 0.033,
    color: theme.colors.textTertiary,
    textAlign: "center",
    marginBottom: 4,
  },
  copyrightSubtext: {
    fontSize: width * 0.03,
    color: theme.colors.textTertiary,
    textAlign: "center",
  },
});
