-- =====================================================
-- BACKUP SCRIPT FOR UNUSED STORED PROCEDURES
-- Generated: January 13, 2026
-- Purpose: Backup all unused procedures before removal
-- =====================================================
-- 
-- HOW TO USE THIS BACKUP:
-- 1. Run this script BEFORE running the cleanup script
-- 2. This will generate CREATE PROCEDURE statements for all procedures being removed
-- 3. Save the output to restore procedures if needed
--
-- To restore a procedure, simply run the CREATE PROCEDURE statement from the backup
-- =====================================================

-- First, let's create a backup table to store procedure definitions
CREATE TABLE IF NOT EXISTS procedure_backup (
    id INT AUTO_INCREMENT PRIMARY KEY,
    procedure_name VARCHAR(255) NOT NULL,
    procedure_definition LONGTEXT,
    backup_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    backup_reason VARCHAR(255) DEFAULT 'Unused procedure cleanup - Jan 2026'
);

-- =====================================================
-- BACKUP AUCTION PROCEDURES (NOT IN USE)
-- =====================================================

INSERT INTO procedure_backup (procedure_name, procedure_definition)
SELECT 
    ROUTINE_NAME,
    ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = DATABASE() 
AND ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_NAME IN (
    -- Auction Procedures (Not in use)
    'sp_activateAuction',
    'sp_cancelAuction',
    'sp_checkAuctionBid',
    'sp_checkExistingAuction',
    'sp_countAuctionBids',
    'sp_countDistinctBidders',
    'sp_createAuction',
    'sp_createAuctionForStall',
    'sp_createAuctionResult',
    'sp_createAuctionWaiting',
    'sp_endAuction',
    'sp_getActiveAuctions',
    'sp_getAuctionBids',
    'sp_getAuctionById',
    'sp_getAuctionByStall',
    'sp_getAuctionByStallId',
    'sp_getAuctionResult',
    'sp_getAuctionWithBidsInfo',
    'sp_getBidCount',
    'sp_getExpiredAuctions',
    'sp_getHighestBid',
    'sp_getUniqueBidders',
    'sp_insertAuctionBid',
    'sp_insertAuctionForStall',
    'sp_logAuctionAction',
    'sp_placeAuctionBid',
    'sp_placeBid',
    'sp_resetWinningBids',
    'sp_selectAuctionWinner',
    'sp_startAuction',
    'sp_updateAuctionCurrentBid',
    'sp_updateAuctionDuration',
    'sp_updateAuctionStatus'
);

-- =====================================================
-- BACKUP RAFFLE PROCEDURES (NOT IN USE)
-- =====================================================

INSERT INTO procedure_backup (procedure_name, procedure_definition)
SELECT 
    ROUTINE_NAME,
    ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = DATABASE() 
AND ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_NAME IN (
    -- Raffle Procedures (Not in use)
    'sp_addRaffleParticipant',
    'sp_cancelRaffle',
    'sp_checkExistingRaffle',
    'sp_checkRaffleEntry',
    'sp_checkRaffleParticipant',
    'sp_countRaffleParticipants',
    'sp_createRaffle',
    'sp_createRaffleForStall',
    'sp_createRaffleResult',
    'sp_createRaffleWaiting',
    'sp_endRaffle',
    'sp_getActiveRaffles',
    'sp_getExpiredRaffles',
    'sp_getRaffleById',
    'sp_getRaffleByStall',
    'sp_getRaffleByStallId',
    'sp_getRaffleEntries',
    'sp_getRaffleParticipants',
    'sp_getRaffleParticipantsByStall',
    'sp_getRaffleResult',
    'sp_getRaffleWithEntriesCount',
    'sp_insertRaffleAuctionLog',
    'sp_insertRaffleEntry',
    'sp_insertRaffleForStall',
    'sp_logRaffleAction',
    'sp_logRaffleAuctionActivity',
    'sp_selectRaffleWinner',
    'sp_setRaffleWinner',
    'sp_updateRaffleDuration',
    'sp_updateRaffleStatus',
    'sp_updateStallRaffleAuctionStatus'
);

-- =====================================================
-- BACKUP OTHER UNUSED PROCEDURES
-- =====================================================

INSERT INTO procedure_backup (procedure_name, procedure_definition)
SELECT 
    ROUTINE_NAME,
    ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = DATABASE() 
AND ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_NAME IN (
    -- Unused General Procedures
    'addDailyPayment',
    'addInspector',
    'assignManagerToBusinessOwner',
    'CanCustomizeDocuments',
    'checkExistingApplicationByStall',
    'CheckExistingOwnerStalls',
    'countApplicationsByBranch',
    'createCollector',
    'createInspectorWithCredentials',
    'createMobileApplication',
    'CreateOwnerWithThreeManagers',
    'createStallApplicationComplete',
    'createStallBusinessOwner',
    'createSystemAdministrator',
    'createVendor',
    'deleteApplicantDocument',
    'deleteBusinessEmployee',
    'deleteCollector',
    'deleteDailyPayment',
    'deleteStall',
    'deleteStallBusinessOwner',
    'deleteStallholder',
    'deleteSystemAdministrator',
    'deleteVendor',
    'getAllApplicants',
    'getAllBusinessEmployees',
    'getAllBusinessOwnersWithSubscription',
    'getAllCollectors',
    'getAllComplaints',
    'getAllComplianceRecords',
    'getAllDailyPayments',
    'getAllDocumentTypes',
    'getAllPayments',
    'getAllStallBusinessOwners',
    'getAllStallholdersDetailed',
    'getAllStallsDetailed',
    'getAllSystemAdministrators',
    'getAllVendors',
    'getApplicantBusinessOwners',
    'getApplicantByUsername',
    'getApplicantDocumentStatus',
    'getApplicantLoginCredentials',
    'getApplicantRequiredDocuments',
    'getApplicationById',
    'getAvailableStalls',
    'getBranchById',
    'getBranchDocumentRequirements',
    'getBusinessOwnerManagers',
    'getCollectorById',
    'getCollectorByUsername',
    'getCollectorsByBranch',
    'getCredentialByApplicantId',
    'getDailyPaymentById',
    'getFloorsByBranch',
    'getInspectorByUsername',
    'getInspectorsByBranch',
    'getManagerBusinessOwners',
    'getMobileUserByUsername',
    'getOnsitePayments',
    'GetOwnerDocumentRequirements',
    'getPaymentStats',
    'getPenaltyPayments',
    'getPenaltyPaymentsByBranches',
    'getSectionsByFloor',
    'getStallBusinessOwnerById',
    'getStallBusinessOwnerByUsername',
    'getStallById',
    'GetStallholderDocuments',
    'getStallholdersByBranch',
    'getSystemAdminDashboardStats',
    'getSystemAdministratorById',
    'getSystemAdministratorByUsername',
    'getVendorById',
    'getVendorsByCollectorId',
    'loginCollector',
    'loginInspector',
    'loginMobileStaff',
    'loginSystemAdministrator',
    'logoutBusinessEmployee',
    'manual_reset_payment_status',
    'processViolationPayment',
    'recordSubscriptionPayment',
    'removeBranchDocumentRequirementById',
    'removeManagerFromBusinessOwner',
    'ResetAllAutoIncrements',
    'ResetAutoIncrement',
    'resetStallBusinessOwnerPassword',
    'resetSystemAdministratorPassword',
    'ResetTableAutoIncrement',
    'resolveComplaint',
    'setBranchDocumentRequirement',
    'terminateCollector',
    'terminateInspector',
    'updateApplicant',
    'updateApplicationStatus',
    'updateBranch',
    'updateBusinessManager',
    'updateCollector',
    'updateCollectorLogin',
    'updateComplaint',
    'updateComplianceRecord',
    'updateDailyPayment',
    'updateFloor',
    'updateMobileApplication',
    'updateSection',
    'updateStall',
    'updateStallBusinessOwner',
    'updateStallholder',
    'updateSystemAdministrator',
    'updateVendor',
    'uploadApplicantDocument'
);

-- =====================================================
-- BACKUP UNUSED SP_ PREFIXED PROCEDURES
-- =====================================================

INSERT INTO procedure_backup (procedure_name, procedure_definition)
SELECT 
    ROUTINE_NAME,
    ROUTINE_DEFINITION
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = DATABASE() 
AND ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_NAME IN (
    -- Unused sp_ procedures (replaced or not needed)
    'sp_addStall',
    'sp_addStallComplete',
    'sp_addStall_complete',
    'sp_add_payment',
    'sp_approveApplication',
    'sp_checkBranchExists',
    'sp_checkCredentialExists',
    'sp_checkExistingDocument',
    'sp_checkInspectorTableExists',
    'sp_checkManagerExistsForBranch',
    'sp_checkManagerExistsForDifferentBranch',
    'sp_checkManagerUsernameExists',
    'sp_checkManagerUsernameGlobal',
    'sp_checkStallAvailability',
    'sp_checkStallExistsMobile',
    'sp_checkStallholderExistsMobile',
    'sp_checkStallImageExistsMobile',
    'sp_checkStallNumberExists',
    'sp_checkUserExists',
    'sp_countApplicantsByStatus',
    'sp_countStallsInSection',
    'sp_createApplication',
    'sp_createBranch',
    'sp_createBranchManager',
    'sp_createCollector',
    'sp_createCollectorAssignment',
    'sp_createComplaint',
    'sp_createDefaultFloor',
    'sp_createDefaultSection',
    'sp_createDocumentRequirement',
    'sp_createFloor',
    'sp_createFloorForImport',
    'sp_createInspector',
    'sp_createInspectorAssignment',
    'sp_createOrUpdateStaffSession',
    'sp_createPayment',
    'sp_createSection',
    'sp_createSectionForImport',
    'sp_createStaffSession',
    'sp_createStaffSessionMinimal',
    'sp_createStall',
    'sp_createStallForImport',
    'sp_createStallholder',
    'sp_createStallholderFromImport',
    'sp_deactivateEmployeeSessions',
    'sp_deactivateStaffSessions',
    'sp_declineApplication',
    'sp_deleteBranch',
    'sp_deleteBranchDocRequirements',
    'sp_deleteBranchDocumentRequirements',
    'sp_deleteBranchManager',
    'sp_deleteDocumentById',
    'sp_deleteDocumentRequirement',
    'sp_deleteStall',
    'sp_deleteStallImageByUrl',
    'sp_deleteStallImageMobile',
    'sp_endStaffSession',
    'sp_findStallByFloorSectionNo',
    'sp_getActiveAdmin',
    'sp_getActiveEmployeeSessions',
    'sp_getActiveEmployeeSessionsByBranch',
    'sp_getActiveSessionsAll',
    'sp_getActiveSessionsByBranches',
    'sp_getAdminByEmail',
    'sp_getAllActiveEmployees',
    'sp_getAllApplicantsByStatus',
    'sp_getAllBranches',
    'sp_getAllBranchManagers',
    'sp_getAllCollectors',
    'sp_getAllCollectorsByBranches',
    'sp_getAllCollectorsWithBranch',
    'sp_getAllEmployeesAll',
    'sp_getAllEmployeesByBranches',
    'sp_getAllFloors',
    'sp_getAllFloorsAdmin',
    'sp_getAllInspectors',
    'sp_getAllInspectorsByBranches',
    'sp_getAllInspectorsWithBranch',
    'sp_getAllSectionsAdmin',
    'sp_getAllStallholderDocuments',
    'sp_getAllStallholderDocumentsWithData',
    'sp_getAllStallholders',
    'sp_getAllStallholdersAll',
    'sp_getAllStallholdersByBranches',
    'sp_getAllStallImagesMobile',
    'sp_getAllStallImagesWithDataMobile',
    'sp_getAllStalls',
    'sp_getAllStallsByBranch',
    'sp_getAllStallsByManager',
    'sp_getAllStalls_complete',
    'sp_getApplicantByIdFull',
    'sp_getApplicantCount',
    'sp_getApplicantDetailsForComplaint',
    'sp_getApplicantForApproval',
    'sp_getApplicantName',
    'sp_getApplicantOtherInfo',
    'sp_getApplicantsByBranch',
    'sp_getApplicantsByBranchManager',
    'sp_getApplicantsByStall',
    'sp_getApplicantsDecrypted',
    'sp_getApplicantWithApplicationDetails',
    'sp_getApplicantWithFullDetails',
    'sp_getApplicationByApplicantId',
    'sp_getApplicationFullDetails',
    'sp_getApplicationsByStatus',
    'sp_getAreaById',
    'sp_getAreas',
    'sp_getAreasByCity',
    'sp_getAvailableStalls',
    'sp_getAvailableStallsByBranch',
    'sp_getAvailableStallsForBranch',
    'sp_getAvailableStallsForImport',
    'sp_getBranchByArea',
    'sp_getBranchDetails',
    'sp_getBranchesByAreaId',
    'sp_getBranchesByManager',
    'sp_getBranchIdFromBusinessManager',
    'sp_getBranchInfo',
    'sp_getBranchManagerByEmail',
    'sp_getBranchNameById',
    'sp_getBusinessEmployeeByEmail',
    'sp_getBusinessEmployeeById',
    'sp_getBusinessManagerByBranch',
    'sp_getBusinessManagerByEmail',
    'sp_getBusinessManagerByEmailForLogin',
    'sp_getBusinessManagerById',
    'sp_getBusinessManagersAllDecrypted',
    'sp_getBusinessOwnerBranches',
    'sp_getBusinessOwnerBranchesWithManagers',
    'sp_getBusinessOwnerBranchIds',
    'sp_getBusinessOwnerByEmail',
    'sp_getBusinessOwnerById',
    'sp_getBusinessOwnerByStall',
    'sp_getBusinessOwnerByUsername',
    'sp_getCities',
    'sp_getCollectorByEmail',
    'sp_getCollectorById',
    'sp_getCollectorByIdDecrypted',
    'sp_getCollectorName',
    'sp_getCollectorNameById',
    'sp_getCollectorsAll',
    'sp_getCollectorsByBranch',
    'sp_getComplaintById',
    'sp_getComplaintsByBranch',
    'sp_getComplaintsByStallholder',
    'sp_getCredentialByApplicantId',
    'sp_getDashboardStats',
    'sp_getDeclinedApplicants',
    'sp_getDistinctAreas',
    'sp_getDistinctBranches',
    'sp_getDocumentBlobById',
    'sp_getDocumentByStallholderType',
    'sp_getDocumentRequirementsByBranch',
    'sp_getDocumentsByStallholder',
    'sp_getDocumentSubmissionBlob',
    'sp_getDocumentTypeById',
    'sp_getDocumentTypeByRequirementId',
    'sp_getDocumentTypes',
    'sp_getEmployeeByEmail',
    'sp_getEmployeeByIdWithBranch',
    'sp_getEmployeeByUsername',
    'sp_getEmployeesByBranchIds',
    'sp_getExistingManagerForBranch',
    'sp_getExistingStallholders',
    'sp_getExistingStallNumbers',
    'sp_getFilteredStalls',
    'sp_getFirstFloorByBranch',
    'sp_getFirstSectionByFloor',
    'sp_getFloorByBranchId',
    'sp_getFloorByBranchWithDetails',
    'sp_getFloorById',
    'sp_getFloorByManagerWithDetails',
    'sp_getFloorCountByManager',
    'sp_getFloorsByBranchId',
    'sp_getFloorsByBranchIds',
    'sp_getFloorSectionDetails',
    'sp_getFloorsWithSections',
    'sp_getInspectorByEmail',
    'sp_getInspectorById',
    'sp_getInspectorByIdDecrypted',
    'sp_getInspectorName',
    'sp_getInspectorNameById',
    'sp_getInspectorsAll',
    'sp_getInspectorsByBranch',
    'sp_getLandingPageStallholders',
    'sp_getLandingPageStalls',
    'sp_getLiveStallData',
    'sp_getLiveStallInfo',
    'sp_getLocationsByBranch',
    'sp_getLocationsByCity',
    'sp_getManagerByUsername',
    'sp_getOnlinePaymentsAll',
    'sp_getOnlinePaymentsByBranches',
    'sp_getOnsitePaymentsAll',
    'sp_getOnsitePaymentsByBranches',
    'sp_getOrCreateDefaultFloor',
    'sp_getOwnerBranches',
    'sp_getParticipantsByBranch',
    'sp_getParticipantsByStall',
    'sp_getPaymentsByStallholder',
    'sp_getPenaltyPayments',
    'sp_getPenaltyPaymentsAll',
    'sp_getPenaltyPaymentsByBranches',
    'sp_getPenaltyPaymentsCount',
    'sp_getRefreshToken',
    'sp_getRefreshTokenInfo',
    'sp_getRegistrationId',
    'sp_getRemainingStallImagesMobile',
    'sp_getSectionByFloorId',
    'sp_getSectionById',
    'sp_getSectionsByFloor',
    'sp_getSectionsByFloorId',
    'sp_getSectionsByFloorIds',
    'sp_getSectionsByFloors',
    'sp_getStallAvailabilityStatus',
    'sp_getStallById',
    'sp_getStallByNumberAndSection',
    'sp_getStallByStallholder',
    'sp_getStallByStallNo',
    'sp_getStallFirstImageMobile',
    'sp_getStallFullDetails',
    'sp_getStallholderByApplicantIdSimple',
    'sp_getStallholderCountByBranch',
    'sp_getStallholderDetailById',
    'sp_getStallholderDetailsForComplaint',
    'sp_getStallholderForPayment',
    'sp_getStallholderFullDetails',
    'sp_getStallholderInfoForStall',
    'sp_getStallholderMasterlist',
    'sp_getStallholdersDecrypted',
    'sp_getStallIdFromImageMobile',
    'sp_getStallImage',
    'sp_getStallImageByIdMobile',
    'sp_getStallImageByPositionMobile',
    'sp_getStallImageForDeleteMobile',
    'sp_getStallImageInfoByIdMobile',
    'sp_getStallImagesWithBranch',
    'sp_getStallPrimaryImageInfo',
    'sp_getStallPrimaryImageMobile',
    'sp_getStallsByArea',
    'sp_getStallsByBranch',
    'sp_getStallsBySectionPaginated',
    'sp_getSubmissionBlobById',
    'sp_getSystemAdminByEmail',
    'sp_get_all_stallholders',
    'sp_get_payments_for_manager',
    'sp_get_stallholders_for_manager',
    'sp_get_stallholder_details',
    'sp_importStallholder',
    'sp_insertApplication',
    'sp_insertBranchDocRequirement',
    'sp_insertBranchManager',
    'sp_insertCredential',
    'sp_insertDocumentBlob',
    'sp_insertFloor',
    'sp_insertSection',
    'sp_insertStall',
    'sp_insertStallholderFromApplication',
    'sp_insertStallImage',
    'sp_insertSubmissionBlob',
    'sp_logStaffActivityAutoLogout',
    'sp_revokeAllUserTokens',
    'sp_revokeRefreshToken',
    'sp_searchApplicants',
    'sp_searchStallholders',
    'sp_setFirstImageAsPrimaryMobile',
    'sp_setStallImagePrimaryMobile',
    'sp_updateApplicantStatus',
    'sp_updateApplicationStatus',
    'sp_updateBranch',
    'sp_updateBranchManager',
    'sp_updateBusinessEmployeeLastLogin',
    'sp_updateBusinessManagerLastLogin',
    'sp_updateBusinessOwnerLastLogin',
    'sp_updateCollectorLastLogout',
    'sp_updateCollectorStatus',
    'sp_updateComplaintStatus',
    'sp_updateCredential',
    'sp_updateCredentialLastLogin',
    'sp_updateCredentialPassword',
    'sp_updateDocumentBlob',
    'sp_updateDocumentRequirement',
    'sp_updateEmployeeSession',
    'sp_updateEmployeeSessionActivity',
    'sp_updateInspectorLastLogout',
    'sp_updateInspectorStatus',
    'sp_updateLastLogin',
    'sp_updateStaffSessionActivity',
    'sp_updateStall',
    'sp_updateStallForOccupancy',
    'sp_updateStallForOccupancyWithDetails',
    'sp_updateStallholderInfo',
    'sp_updateStallImageBlobMobile',
    'sp_updateStallImageOrderMobile',
    'sp_updateStallOccupied',
    'sp_updateStallRentalPrice',
    'sp_updateStallStatus',
    'sp_updateStall_complete',
    'sp_updateSubmissionBlob',
    'sp_updateSystemAdminLastLogin',
    'sp_updateSystemAdminLastLogoutNow',
    'sp_updateUserLastLogin',
    'sp_uploadApplicantDocument',
    'sp_uploadStallImage',
    'sp_verifyDocumentExists',
    'sp_verifyStallholderExists'
);

-- Show what was backed up
SELECT 
    procedure_name,
    backup_date,
    backup_reason,
    CASE 
        WHEN procedure_definition IS NOT NULL THEN 'Backed up successfully'
        ELSE 'Definition not captured (may need manual backup)'
    END as status
FROM procedure_backup
ORDER BY procedure_name;

-- Count of backed up procedures
SELECT COUNT(*) as total_backed_up FROM procedure_backup;

SELECT '=======================================' as '';
SELECT 'BACKUP COMPLETE!' as message;
SELECT 'Run CLEANUP_UNUSED_PROCEDURES.sql to remove procedures' as next_step;
SELECT '=======================================' as '';
