-- Check all procedures related to stallholders
SELECT ROUTINE_NAME 
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = 'naga_stall' 
AND ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_NAME LIKE '%stall%'
ORDER BY ROUTINE_NAME;
