// Network configuration for mobile app
// Use this file to configure the API endpoints for your React Native Expo app

// IMPORTANT: This configuration supports multiple network environments
// It will automatically try different endpoints until one works

// ===== AUTO-DETECT ENVIRONMENT =====
// __DEV__ is a React Native global:
//   true  → Expo Go / development mode  → use LOCAL backend
//   false → APK / production build       → use DigitalOcean backend
const IS_DEV = typeof __DEV__ !== 'undefined' ? __DEV__ : false;

// ===== AUTO-DETECT LOCAL IP FROM EXPO =====
// Expo Metro bundler knows the correct LAN IP for any WiFi network.
// We extract it from Constants.expoConfig.hostUri (format: "IP:PORT")
// This means you NEVER have to hardcode your home IP again.
import Constants from 'expo-constants';

const getDevHostIP = () => {
  try {
    const hostUri = Constants.expoConfig?.hostUri  // e.g. "178.16.104.68:8081"
                 || Constants.manifest?.debuggerHost  // older SDK fallback
                 || Constants.manifest2?.extra?.expoGo?.debuggerHost;
    if (hostUri) {
      const ip = hostUri.split(':')[0]; // strip the port
      if (ip && ip !== 'localhost' && ip !== '127.0.0.1') {
        console.log(`🔍 Auto-detected dev machine IP: ${ip}`);
        return ip;
      }
    }
  } catch (e) {
    console.log('⚠️ Could not auto-detect IP from Expo:', e.message);
  }
  return null;
};

// Server lists by environment
const PRODUCTION_SERVERS = [
  'http://digi-stall.com:5001',    // Domain Backend-Mobile API (PRIMARY)
  'http://68.183.154.125:5001',    // IP Backend-Mobile API (fallback)
  'http://digi-stall.com:5000',    // Domain Backend-Web API (fallback)
  'http://68.183.154.125:5000',    // IP Backend-Web API (fallback)
];

// Build dev servers dynamically from auto-detected IP
const detectedIP = IS_DEV ? getDevHostIP() : null;

const DEVELOPMENT_SERVERS = detectedIP
  ? [
      `http://${detectedIP}:5001`,   // Local Backend-Mobile API (primary)
      `http://${detectedIP}:5000`,   // Local Backend-Web API (fallback)
      `http://${detectedIP}:3001`,   // Local single-server fallback
      'http://localhost:3001',       // Only works on emulator
    ]
  : [
      'http://192.168.1.105:5001',   // Hardcoded fallback if auto-detect fails
      'http://192.168.1.105:5000',
      'http://192.168.1.105:3001',
      'http://localhost:3001',
    ];

export const API_CONFIG = {
  // Server endpoints are ordered automatically based on environment
  // Expo Go (dev) → local servers first, APK (prod) → DigitalOcean first
  SERVERS: IS_DEV
    ? [...DEVELOPMENT_SERVERS, ...PRODUCTION_SERVERS]   // Dev: try local first, fallback to production
    : [...PRODUCTION_SERVERS, ...DEVELOPMENT_SERVERS],  // Prod: try DigitalOcean first, fallback to local
  
  // Static file server for images (Apache on port 80)
  // Must match one of the server IPs above
  STATIC_FILE_SERVER: null,
  
  // Current active server (will be set automatically)
  BASE_URL: null,
  
  // Mobile app specific endpoints
  MOBILE_ENDPOINTS: {
    // Authentication endpoints - Match Backend-Mobile routes (using /api/mobile/ prefix)
    LOGIN: '/api/mobile/auth/login',
    STAFF_LOGIN: '/api/mobile/auth/staff-login',
    REGISTER: '/api/mobile/auth/register',
    VERIFY_TOKEN: '/api/mobile/auth/verify-token',
    LOGOUT: '/api/mobile/auth/logout',
    STAFF_LOGOUT: '/api/mobile/auth/staff-logout',
    STAFF_HEARTBEAT: '/api/mobile/auth/staff-heartbeat',
    STAFF_AUTO_LOGOUT: '/api/mobile/auth/staff-auto-logout',
    CHANGE_PASSWORD: '/api/mobile/auth/change-password',
    
    // Forgot Password / Password Reset endpoints (using unified auth endpoints)
    FORGOT_PASSWORD_VERIFY_EMAIL: '/api/auth/verify-email-exists',
    FORGOT_PASSWORD_SEND_CODE: '/api/auth/resend-reset-code',  // Backend generates code, sends via email, and stores
    FORGOT_PASSWORD_STORE_CODE: '/api/auth/store-reset-code',   // Client-side EmailJS flow: store code generated by client
    FORGOT_PASSWORD_VERIFY_CODE: '/api/auth/verify-reset-code',
    FORGOT_PASSWORD_RESET: '/api/auth/reset-password',
    
    // Stall endpoints
    GET_ALL_STALLS: '/api/mobile/stalls',
    GET_STALLS_BY_TYPE: '/api/mobile/stalls/type',
    GET_STALLS_BY_AREA: '/api/mobile/stalls/area',
    GET_STALL_BY_ID: '/api/mobile/stalls',
    GET_STALL_IMAGES: '/api/mobile/stalls/images',
    GET_AVAILABLE_AREAS: '/api/mobile/areas',
    SEARCH_STALLS: '/api/mobile/stalls/search',
    
    // Application endpoints
    SUBMIT_APPLICATION: '/api/mobile/applications/submit',
    JOIN_RAFFLE: '/api/mobile/applications/join-raffle',
    JOIN_AUCTION: '/api/mobile/applications/join-auction',
    GET_MY_APPLICATIONS: '/api/mobile/applications/my',
    GET_APPLICATION_STATUS: '/api/mobile/applications',
    UPDATE_APPLICATION: '/api/mobile/applications',

    // Stallholder document endpoints
    GET_STALLHOLDER_STALLS_DOCUMENTS: '/api/mobile/stallholder/documents',
    GET_BRANCH_DOCUMENT_REQUIREMENTS: '/api/mobile/stallholder/documents/branch',
    UPLOAD_STALLHOLDER_DOCUMENT: '/api/mobile/stallholder/documents/upload',
    
    // Inspector endpoints
    GET_INSPECTOR_STALLHOLDERS: '/api/mobile/inspector/stallholders',
    GET_STALLHOLDER_DETAILS: '/api/mobile/inspector/stallholders',
    GET_VIOLATION_TYPES: '/api/mobile/inspector/violations',
    SUBMIT_VIOLATION_REPORT: '/api/mobile/inspector/report',
    SUBMIT_VIOLATION_REPORT_WITH_PHOTOS: '/api/mobile/inspector/report-with-photos',
    GET_INSPECTOR_SENT_REPORTS: '/api/mobile/inspector/sent-reports',
    
    // Stallholder complaint endpoints
    SUBMIT_COMPLAINT: '/api/mobile/stallholder/complaint',
    GET_MY_COMPLAINTS: '/api/mobile/stallholder/complaints',
    
    // Stallholder owned stalls endpoint
    GET_OWNED_STALLS: '/api/mobile/stallholder/owned-stalls',
    
    // Stallholder joined stalls endpoint
    GET_JOINED_STALLS: '/api/mobile/stallholder/joined-stalls',
    
    // Stallholder payment endpoints
    GET_PAYMENT_RECORDS: '/api/mobile/stallholder/payments',
    GET_ALL_PAYMENT_RECORDS: '/api/mobile/stallholder/payments/all',
    GET_PAYMENT_SUMMARY: '/api/mobile/stallholder/payments/summary',
    GET_MONTHLY_PAYMENT_STATUS: '/api/mobile/stallholder/payments/monthly-status',
    
    // Health check
    HEALTH: '/api/health'  // Unified server health endpoint
  },
  
  // Timeout for network requests (5 seconds - balanced for reliability)
  TIMEOUT: 5000,
  
  // Default headers
  HEADERS: {
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  }
};

// Server discovery and connection testing
export const NetworkUtils = {
  // Test if a server is reachable (quick check)
  async testConnection(serverUrl, quickCheck = false) {
    try {
      console.log(`🔌 Testing connection to: ${serverUrl}`);
      
      const controller = new AbortController();
      const timeout = quickCheck ? 3000 : API_CONFIG.TIMEOUT; // 3s for quick, 5s for full
      const timeoutId = setTimeout(() => controller.abort(), timeout);
      
      // Try health endpoint first
      let response;
      try {
        response = await fetch(`${serverUrl}${API_CONFIG.MOBILE_ENDPOINTS.HEALTH}`, {
          method: 'GET',
          headers: API_CONFIG.HEADERS,
          signal: controller.signal
        });
      } catch (healthError) {
        // If health endpoint fails, try root endpoint
        console.log(`🔄 Health endpoint failed, trying root...`);
        response = await fetch(`${serverUrl}/`, {
          method: 'GET',
          signal: controller.signal
        });
      }
      
      clearTimeout(timeoutId);
      
      if (response.ok || response.status < 500) {
        console.log(`✅ Connection successful to: ${serverUrl}`);
        return true;
      } else {
        console.log(`❌ Server responded with error: ${response.status}`);
        return false;
      }
    } catch (error) {
      console.log(`❌ Connection failed to ${serverUrl}:`, error.message);
      return false;
    }
  },

  // Find the first working server
  async findWorkingServer() {
    console.log('🔍 Discovering available servers...');
    
    // Test servers sequentially (more reliable than parallel for mobile)
    for (const server of API_CONFIG.SERVERS) {
      const works = await this.testConnection(server, true);
      if (works) {
        API_CONFIG.BASE_URL = server;
        try {
          const url = new URL(server);
          API_CONFIG.STATIC_FILE_SERVER = `http://${url.hostname}`;
        } catch (e) {
          API_CONFIG.STATIC_FILE_SERVER = server;
        }
        console.log(`🎯 Active server set to: ${server}`);
        return server;
      }
    }
    
    console.error('❌ No working servers found');
    throw new Error('Unable to connect to any server. Please check:\n\n• Backend-Mobile server is running (port 5001)\n• Device has internet connection\n• Your IP is in the server list');
  },

  // Get current active server or find one
  async getActiveServer() {
    if (API_CONFIG.BASE_URL) {
      // Test if current server is still working
      if (await this.testConnection(API_CONFIG.BASE_URL)) {
        return API_CONFIG.BASE_URL;
      } else {
        console.log('🔄 Current server not responding, finding new one...');
        API_CONFIG.BASE_URL = null;
        API_CONFIG.STATIC_FILE_SERVER = null;
      }
    }
    
    return await this.findWorkingServer();
  },
  
  // Get static file server URL (for images served by Apache)
  getStaticFileServer() {
    // If we have BASE_URL, always extract the hostname from it
    if (API_CONFIG.BASE_URL) {
      try {
        const url = new URL(API_CONFIG.BASE_URL);
        API_CONFIG.STATIC_FILE_SERVER = `http://${url.hostname}`;
      } catch (e) {
        // Fallback: extract IP from URL string
        const match = API_CONFIG.BASE_URL.match(/http:\/\/([^:]+)/);
        if (match) {
          API_CONFIG.STATIC_FILE_SERVER = `http://${match[1]}`;
        }
      }
    }
    return API_CONFIG.STATIC_FILE_SERVER || 'http://localhost';
  },
  
  // Get API base URL for API calls (including BLOB image endpoints)
  getApiUrl() {
    return API_CONFIG.BASE_URL || 'http://localhost:3001';
  }
};

// Helper function to make API calls
export const apiCall = async (endpoint, method = 'GET', data = null) => {
  try {
    const config = {
      method,
      headers: API_CONFIG.HEADERS,
      timeout: API_CONFIG.TIMEOUT
    };
    
    if (data && (method === 'POST' || method === 'PUT')) {
      config.body = JSON.stringify(data);
    }
    
    const response = await fetch(`${API_CONFIG.BASE_URL}${endpoint}`, config);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }
    
    return await response.json();
  } catch (error) {
    console.error(`API call failed for ${endpoint}:`, error);
    throw error;
  }
};

// Example usage in your mobile app:
// import { API_CONFIG, apiCall } from './config/networkConfig';
// 
// // Login example:
// const loginResult = await apiCall(API_CONFIG.MOBILE_ENDPOINTS.LOGIN, 'POST', {
//   username: 'your_username',
//   password: 'your_password'
// });

console.log('📱 Mobile Network Config Loaded');
console.log(`🔧 Environment: ${IS_DEV ? 'DEVELOPMENT (Expo Go → Local Backend)' : 'PRODUCTION (APK → DigitalOcean)'}`);
if (IS_DEV && detectedIP) {
  console.log(`🔍 Auto-detected LAN IP: ${detectedIP} (works on any WiFi)`);
} else if (IS_DEV) {
  console.log('⚠️ Could not auto-detect IP, using hardcoded fallback');
}
console.log('🌐 Server priority:', API_CONFIG.SERVERS.map(s => s.replace('http://', '')).join(' → '));
console.log('🌐 Backend URL:', API_CONFIG.BASE_URL);